### ISSUE TITLE
Nonsensical mixing ratios

### ISSUE THREAD

**Issue by SmithJK** [GRIFFINCollaboration/Geant4GammaGammaAngularCorrelations10.01.p01#2]
If the multipole data file lists the same multipolarity twice, any mixing ratio besides 0 will give incorrect a2 and a4 values rather than flagging the input as nonsensical and correcting it.

Example `UserMultipoleData_z28.a60`:

```
1.3325180000e+03 1.332501e+03 2 2 0.5
2.5057660000e+03 1.173237e+03 2 0 0
```

This produces a2 and a4 values of 0.183673 and 0.0163265, respectively. Changing the mixing ratio to 0 gives the appropriate values of 0.102041 and 0.00907029. Is there a good function to include a check in?

**Comment by evan012345** [comment]
Hey Jenna,
You're right, those a2's and a4's are nonsensical, but to be fair, so is the input. But if you want to include a check, that doesn't hurt. We could add a check in one of two places, the ReadDataLineMultipole function in the G4NuclearLevelManager.cc, or the GenerateWThetaParameters function in G4NuclearLevel.cc. The former is where the multipole file is read in, and the latter is where the W(theta) function is calculated. I would say it probably makes the most sense to include a check in the GenerateWThetaParameters function in G4NuclearLevel.cc. 

Did you want to include the check? Or I can, if you like.

**Comment by SmithJK** [comment]
I can include it.

Jenna

**Comment by SmithJK** [comment]
Turns out I haven't forked this yet, only cloned it. I suggest then, that you include the check. Though, since I wrote the check before I realized this...

```
  // a check for non-sensical spin/mixing ratio combinations
  if (L1==L1p) delta1 = 0;
  if (L2==L2p) delta2 = 0;
```

**Comment by evan012345** [comment]
Done. Thanks Jenna.
