### ISSUE TITLE
Radioactive Data - Environmental Variables

### ISSUE THREAD

**Issue by lunab984** [GRIFFINCollaboration/Geant4GammaGammaAngularCorrelations10.01.p01#9]
I am attempting to run the angular correlations patch to GEANT4 on version 10.01.p03. I have followed the instructions in the README and have noted that one issue above this one mentions needing to change the references in CMakeList.txt from "rdecay01" to "rdecay01_ggac". I have successfully done this on Linux Mint and Ubuntu, and compilation is without any errors. In running the executable, however, I get two errors on the Ubuntu machine and a different error on the Linux Mint machine:
![Geant4Problem1](https://user-images.githubusercontent.com/18104018/61977062-05a1b000-afb3-11e9-8191-80df2edd825f.png)

![Geant4Problem2](https://user-images.githubusercontent.com/18104018/61977076-0f2b1800-afb3-11e9-9257-e3755395a929.png)

The problem on the Linux Mint machine is similar to the second but referring to the G4ENSDFDATA environmental variables (the version number of the ENSDF data set is out of date), and I can't even run the given basic examples. I'm unsure of what to reference or where to reference it.

I also notice that OpenGL is causing problems in both. Is this the normative graphics program that everyone runs, or is there another one regularly used?

**Comment by VinzenzBildstein** [comment]
I don't think that the angular correlations patch works with the newer versions of GEANT4. As of Geant4.10.04 there is native support for angular correlations (see GRIFFINCollaboration/detectorSimulations_v10#40).

**Comment by lunab984** [comment]
So is the branch mentioned in the issue referenced the current working version for GRIFFIN - in other words, has it been updated since the release of GEANT4.10.05?

**Comment by VinzenzBildstein** [comment]
No, I don't think so. The branch geant4.10.04 has been last update on June 22nd 2018 and Geant4.10.05 has been released in December 2018. But that doesn't mean that this branch couldn't work with 10.05, I don't know if anyone tested that.
